Test Error
Error CS0122 'Program.FullName(string, string)' is inaccessible due to its protection level Test C:\Users\Sarah Budwell\source\repos\sarahBud\CoderGirl-FullName\Test\ProgramTest.cs 73 Active